AllCops:
  TargetRubyVersion: 2.4.5
  Exclude:
    - Rakefile

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false
