AllCops:
  TargetRubyVersion: 2.4.5
  Exclude:
    - Rakefile
    - to_decimal.gemspec

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: group
  Exclude:
    - lib/to_decimal.rb

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false
